Support to collect queries from http basic auth enabled cluster
varadaio/presto-workload-analyzer pull request #1
Opened 2021-03-04 11:02 UTC by ashishtadose

2021-03-08 19:52 UTC, romanvainbrand commented
Hi Ashish,
Thanks for your contribution.
I wonder if we add params such as username and password to get wouldn't it be better create a class which will get all params in __init__ and all the get calls will stay clean.

@ashishtadose @guy
WDYT?

2021-09-06 14:05 UTC, sbernauer requested changes
Hi @ashishtadose thanks for you patch! I did notice a small problem (see Review)
@ashishtadose and @guy feedback regarding @romanvainbrand's comment would be great!

2021-09-06 14:05 UTC, sbernauer commented on analyzer/collect.py
> +                response = get(endpoint, args.username, args.password)
I tested out for patch. Needed quite some time to find the problem. This should be
`response = get(url, args.username, args.password)`

2021-09-09 13:25 UTC, Guy-Mast commented
Hi @sbernauer and all,
I will work on incorporating all the inputs shared in this PR and thread and will provide an updated PR.

2021-09-16 08:44 UTC, Guy-Mast commented
all,
please see the new PR https://github.com/varadaio/presto-workload-analyzer/pull/5 which is based on @ashishtadose work here and takes into consideration the follow-up feedbacks we got.

please let me know if you have any comments.

2021-09-23 12:59 UTC, closed without merging